### ISSUE TITLE
Getting Errors when loading Antimatter Annihilation mod

### ISSUE THREAD

**Issue by ArunPrasath-M** [Epicguru/AntimatterAnnihilation#3]
in game wiki (dependency) mod seems to be the problem. Captured info is here:
https://gist.github.com/da24cdcb58db3be61550fc351d539b35

**Comment by Epicguru** [comment]
Looks like you aren't using Steam. I've uploaded a new version here on Github, please download it as well as the latest InGameWiki version.

**Comment by ArunPrasath-M** [comment]
I'm afraid I'm still getting the error.  Captured the (new?) error logs here: https://gist.github.com/16b986d7104319b04554e0a60a583490.

Did the following: 
1. Downloaded the update 3 from https://github.com/Epicguru/AntimatterAnnihilation/releases/download/Update_3/Antimatter.Annihilation.zip
2. Re-Downloaded the code from in-game Wiki (Code->Download zip from https://github.com/Epicguru/InGameWiki)

Deleted the existing mods in my Mods folder and extracted the above 2 folders into it (ie, Mods/InGameWiki-master and Mods/Antimatter Annihilation).

**Comment by Epicguru** [comment]
Okay, it doesn't work because the assemblies aren't included in the in-game wiki mod Github repository. I'll upload a zip file for InGameWiki that you can download.

https://github.com/Epicguru/InGameWiki/releases/tag/Release

**Comment by ArunPrasath-M** [comment]
Awesome dude! That fixed it fully. Will get back if I'm seeing errors in game play :). Thanks for your prompt response!

**Comment by Epicguru** [comment]
No problem, enjoy. I'll close this issue now.
